#$schema: https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Futured CI/CD Workflows
site_url: https://futuredapp.github.io/.github
theme:
  name: material
  language: en

  custom_dir: docs/overrides

  favicon: assets/images/favicon.png
  icon:
    logo: futured/logo

  font:
    code: JetBrains Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - glightbox:
      background: light-dark(white, black)
      shadow: false

nav:
  - Home: index.md
  - Workflows:
      - Overview: workflows/index.md
      - iOS:
          - workflows/ios/index.md
          - Test: workflows/ios/selfhosted-test.md
          - Nightly Build: workflows/ios/selfhosted-nightly-build.md
          - On-demand Build: workflows/ios/selfhosted-on-demand-build.md
          - Release: workflows/ios/selfhosted-release.md
          - Build (Deprecated): workflows/ios/selfhosted-build.md
      - iOS + KMP:
          - workflows/ios-kmp/index.md
          - Test: workflows/ios-kmp/selfhosted-test.md
          - Build: workflows/ios-kmp/selfhosted-build.md
          - Release: workflows/ios-kmp/selfhosted-release.md
      - Android:
          - workflows/android/index.md
          - PR Check: workflows/android/cloud-check.md
          - Nightly Build: workflows/android/cloud-nightly-build.md
          - Release (Firebase): workflows/android/cloud-release-firebase.md
          - Release (Google Play): workflows/android/cloud-release-googleplay.md
          - Generate Baseline Profiles: workflows/android/cloud-generate-baseline-profiles.md
      - KMP:
          - workflows/kmp/index.md
          - Detect Changes: workflows/kmp/cloud-detect-changes.md
          - Combined Nightly Build: workflows/kmp/combined-nightly-build.md
      - Universal:
          - workflows/universal/index.md
          - Workflows Lint: workflows/universal/workflows-lint.md
          - Cloud Backup: workflows/universal/cloud-backup.md
          - Self-hosted Backup: workflows/universal/selfhosted-backup.md
  - Actions:
      - Overview: actions/index.md
      - Android:
          - actions/android/index.md
          - Setup Environment: actions/android/setup-environment.md
          - Check: actions/android/check.md
          - Build Firebase: actions/android/build-firebase.md
          - Build Google Play: actions/android/build-googleplay.md
          - Generate Baseline Profiles: actions/android/generate-baseline-profiles.md
      - iOS:
          - actions/ios/index.md
          - Export Secrets: actions/ios/export-secrets.md
          - Fastlane Test: actions/ios/fastlane-test.md
          - Fastlane Beta: actions/ios/fastlane-beta.md
          - Fastlane Release: actions/ios/fastlane-release.md
          - KMP Build: actions/ios/kmp-build.md
      - Utility:
          - actions/utility/index.md
          - KMP Detect Changes: actions/utility/kmp-detect-changes.md
          - Detect Changes & Changelog: actions/utility/detect-changes-changelog.md
          - JIRA Transition Tickets: actions/utility/jira-transition-tickets.md

copyright: Made with ‚ù§Ô∏è‚Äçüî• at Futured

extra:
  version:
    provider: mike
  social:
    - icon: material/web
      name: Web
      link: https://www.futured.app
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://www.github.com/futuredapp
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/company/futuredapps
    - icon: fontawesome/brands/instagram
      name: Instagram
      link: https://www.instagram.com/futuredapps

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
