name: iOS Self-hosted Nightly Build

on:
  workflow_call:
    inputs:
      # General
      runner_label:
        description: 'The custom label for the self-hosted runner to use for the build job.'
        type: string
        default: 'self-hosted'
      timeout_minutes:
        description: 'Job timeout in minutes'
        type: number
        default: 30
      # Changelog
      checkout_depth:
        description: 'The depth of the git history to fetch for changelog generation.'
        type: number
        required: false
        default: 100
      changelog_fallback_lookback:
        description: 'The amount of time to look back for merge commits when no previous build commit is found. Default is 24 hours.'
        type: string
        required: false
        default: '24 hours'
      # Git LFS
      use_git_lfs:
        description: 'Whether to download Git-LFS files.'
        type: boolean
        default: false
      # Export secrets
      xcconfig_path:
        description: 'Path to the .xcconfig file. Selected secret properties will be appended to the end of this file.'
        type: string
        required: false
      required_keys:
        description: 'Comma-separated list of required keys.'
        type: string
        required: false
      # Custom values
      custom_values:
        description: 'Custom string that can contains values specified in your workflow file. Those values will be placed into environment variable. Example: "CUSTOM-1: 1; CUSTOM-2: 2"'
        type: string
        required: false
        default: '24 hours'
      jira_transition:
        description: 'The name of the JIRA transition to apply to tickets found in merged branches.'
        type: string
        required: false
        default: 'Testing'

    secrets:
      MATCH_PASSWORD:
        required: true
        description: 'Password for decrypting of certificates and provisioning profiles.'
      APP_STORE_CONNECT_API_KEY_KEY:
        required: true
        description: 'Private App Store Connect API key for submitting build to App Store.'
      APP_STORE_CONNECT_API_KEY_KEY_ID:
        required: true
        description: 'Private App Store Connect API key for submitting build to App Store.'
      APP_STORE_CONNECT_API_KEY_ISSUER_ID:
        required: true
        description: 'Private App Store Connect API issuer key for submitting build to App Store.'
      SECRET_PROPERTIES:
        required: false
        description: 'Secrets in the format KEY = VALUE (one per line).'
      JIRA_CONTEXT:
        required: false
        description: 'JIRA context for transitioning tickets.'

jobs:
  build:
    runs-on: ${{ fromJson(format('["self-hosted", "{0}"]', inputs.runner_label)) }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    outputs:
      skip_build: ${{ steps.detect_changes.outputs.skip_build }}
      merged_branches: ${{ steps.detect_changes.outputs.merged_branches }}

    steps:
      - name: Detect changes and generate changelog
        id: detect_changes
        uses: futuredapp/.github/.github/actions/universal-detect-changes-and-generate-changelog@main
        with:
          checkout_depth: ${{ inputs.checkout_depth }}
          fallback_lookback: ${{ inputs.changelog_fallback_lookback }}
          use_git_lfs: ${{ inputs.use_git_lfs }}
  
      - name: Set changelog
        if: ${{ steps.detect_changes.outputs.skip_build == 'false' }}
        id: set_changelog
        run: |
          echo "changelog=${{ steps.detect_changes.outputs.changelog }}" >> "$GITHUB_OUTPUT"

      - name: Export secrets
        if: ${{ steps.detect_changes.outputs.skip_build == 'false' && inputs.xcconfig_path != '' }}
        uses: futuredapp/.github/.github/actions/ios-export-secrets@main
        with:
          XCCONFIG_PATH: ${{ inputs.xcconfig_path }}
          SECRET_PROPERTIES: ${{ secrets.SECRET_PROPERTIES }}
          REQUIRED_KEYS: ${{ inputs.required_keys }}

      - name: Fastlane Beta
        if: ${{ steps.detect_changes.outputs.skip_build == 'false' }}
        uses: futuredapp/.github/.github/actions/ios-fastlane-beta@main
        with:
          match_password: ${{ secrets.MATCH_PASSWORD }}
          testflight_changelog: ${{ steps.set_changelog.outputs.changelog }}
          app_store_connect_api_key_key: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          app_store_connect_api_key_key_id: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          app_store_connect_api_key_issuer_id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          custom_values: ${{ inputs.custom_values }}

      - name: Upload IPA
        if: ${{ steps.detect_changes.outputs.skip_build == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: Build.ipa
          path: build_output/*.ipa

      - name: Upload dSYM
        if: ${{ steps.detect_changes.outputs.skip_build == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: Build.app.dSYM.zip
          path: build_output/*.app.dSYM.zip

      - name: Save latest build commit SHA to file
        if: success() && steps.detect_changes.outputs.skip_build == 'false'
        shell: bash
        run: |
          echo "${{ github.sha }}" > latest_builded_commit.txt
      
      - name: Store latest build commit SHA in cache
        if: success() && steps.detect_changes.outputs.skip_build == 'false'
        uses: actions/cache/save@v4
        with:
          path: latest_builded_commit.txt
          key: ${{ steps.detect_changes.outputs.cache_key }}

  transition_jira_tickets:
    name: Transition JIRA tickets
    runs-on: ubuntu-latest
    needs: build
    if: success() && needs.build.outputs.skip_build != 'true'
    steps:
      - name: Check JIRA context
        id: check
        env:
          JIRA_CONTEXT: ${{ secrets.JIRA_CONTEXT }}
        run: |
          if [ -z "$JIRA_CONTEXT" ]; then
            echo "enabled=false" >> "$GITHUB_OUTPUT"
            echo "â„¹ï¸ JIRA ticket transition skipped - no JIRA context provided."
            echo "ðŸ’¡ Tip: You can automatically transition JIRA tickets by passing the 'JIRA_CONTEXT' secret."
          else
            echo "enabled=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Transition JIRA tickets
        if: steps.check.outputs.enabled == 'true'
        uses: futuredapp/.github/.github/actions/jira-transition-tickets@main
        with:
          jira_context: ${{ secrets.JIRA_CONTEXT }}
          transition: ${{ inputs.jira_transition }}
          merged_branches: ${{ needs.build.outputs.merged_branches }}
