name: Check Pull Request

on: [pull_request]

jobs:
  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Add problem matcher
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash

  tests:
    name: Test Actions
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bats
        id: install_bats
        uses: bats-core/bats-action@3.0.1
      - name: Run tests
        shell: bash
        run: bats -r .
